"""Prompts package for AI Stylist."""

from .analyzer import (
    USER_ANALYSIS_PROMPT,
    QUERY_ANALYSIS_PROMPT,
    SEARCH_KEYWORDS_PROMPT,
    GARMENT_CLASSIFICATION_PROMPT,
)
from .stylist import STYLIST_PROMPT, OUTFIT_SELECTION_PROMPT

__all__ = [
    "USER_ANALYSIS_PROMPT",
    "QUERY_ANALYSIS_PROMPT",
    "SEARCH_KEYWORDS_PROMPT",
    "GARMENT_CLASSIFICATION_PROMPT",
    "STYLIST_PROMPT",
    "OUTFIT_SELECTION_PROMPT",
]
